"use client";
import {useEffect,useState} from "react";
type Item={id:string;name:string;cin?:string|null;gstin?:string|null;createdAt:string;owner:{name:string;email:string;phone?:string|null};certificateAvailable:boolean};
export default function EmployerApprovals(){
 const [items,setItems]=useState<Item[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 const load=()=>fetch("/api/admin/employer-approvals").then(r=>r.ok?r.json():[]).then(setItems);
 useEffect(()=>{load()},[]);
 async function act(id:string,action:"APPROVE"|"REJECT"){const note=window.prompt(action==="APPROVE"?"Approval note (optional)":"Reason for rejection");if(action==="REJECT"&&!note?.trim())return;setBusy(id);const r=await fetch("/api/admin/employer-approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:id,action,note:note||""})});const d=await r.json();setBusy("");setMsg(r.ok?"Employer account updated.":d.error||"Update failed");if(r.ok)load()}
 return <main className="wrap"><div className="card"><div className="pill">PLATFORM ADMIN</div><h1>Employer account approvals</h1><p className="muted">Review company identity details and the registration certificate before approving employer access.</p>{msg&&<p className="notice">{msg}</p>}</div><section className="section">{items.length?<div className="grid">{items.map(x=><div className="card" key={x.id}><div className="pill">PENDING</div><h3>{x.name}</h3><p>Representative: {x.owner.name}</p><p>Email: {x.owner.email}</p>{x.owner.phone&&<p>Phone: {x.owner.phone}</p>}<p>CIN: {x.cin||"—"}</p><p>GSTIN: {x.gstin||"—"}</p><p>Certificate: {x.certificateAvailable?<a href={"/api/admin/employer-approvals?organizationId="+encodeURIComponent(x.id)} target="_blank" rel="noreferrer">View certificate</a>:"Missing"}</p><p className="muted">Submitted {new Date(x.createdAt).toLocaleString()}</p><div className="actions"><button className="btn" disabled={busy===x.id} onClick={()=>act(x.id,"APPROVE")}>Approve</button><button className="btn alt" disabled={busy===x.id} onClick={()=>act(x.id,"REJECT")}>Reject</button></div></div>)}</div>:<div className="card"><h3>No pending employer requests</h3><p className="muted">New employer registrations will appear here.</p></div>}</section></main>
}