"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type RequestItem={id:string;careerId:string;employeeName:string;status:string;consentedAt?:string|null;respondedAt?:string|null;response?:{verified:boolean}|null};
type SelfItem={id:string;careerId:string;employeeName:string;organization:string;designation:string;department?:string|null;employeeCode?:string|null;employmentType?:string|null;joinedAt:string;leftAt?:string|null;remarks?:string|null};
type Correction={id:string;careerId:string;employeeName:string;organization:string;designation:string;department?:string|null;employmentType?:string|null;joinedAt:string;leftAt?:string|null;pendingSince:string};
type Additional={id:string;careerId:string;employeeName:string;designation:string;requestingOrganization:string;question:string;status:string;response?:string|null;createdAt:string};
export default function IncomingVerification(){
 const [items,setItems]=useState<RequestItem[]>([]),[self,setSelf]=useState<SelfItem[]>([]),[corrections,setCorrections]=useState<Correction[]>([]),[additional,setAdditional]=useState<Additional[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=()=>Promise.all([
  fetch("/api/verification/incoming").then(r=>r.ok?r.json():[]).then(setItems),
  fetch("/api/verification/self-added").then(r=>r.ok?r.json():[]).then(setSelf),
  fetch("/api/verification/corrections").then(r=>r.ok?r.json():[]).then(setCorrections),
  fetch("/api/verification/additional-info").then(r=>r.ok?r.json():[]).then(setAdditional),
 ]).finally(()=>setLoading(false));
 useEffect(()=>{load()},[]);
 const respond=async(item:RequestItem,approved:boolean)=>{setBusy(item.id);setMessage("");const r=await fetch("/api/verification/respond",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:item.id,approved})});const d=await r.json();setBusy("");setMessage(r.ok?"Response submitted.":d.error||"Response failed");if(r.ok)load()};
 const selfAction=async(id:string,action:"VERIFY"|"REJECT")=>{setBusy(id);setMessage("");const r=await fetch("/api/verification/self-added",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({employmentId:id,action})});const d=await r.json();setBusy("");setMessage(r.ok?(action==="VERIFY"?"Self-added employment verified.":"Self-added employment rejected."):d.error||"Update failed");if(r.ok)load()};
 const additionalAction=async(id:string)=>{setBusy(id);setMessage("");const response=window.prompt("Enter the information you want to provide to the requesting employer.");if(!response?.trim()){setBusy("");return}const r=await fetch("/api/verification/additional-info",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:id,response:response.trim()})});const d=await r.json();setBusy("");setMessage(r.ok?"Additional information sent.":d.error||"Update failed");if(r.ok)load()};
 const correctionAction=async(id:string,approved:boolean)=>{setBusy(id);setMessage("");const notes=window.prompt(approved?"Optional note for the employee":"Reason for not re-verifying (optional)")||"";const r=await fetch("/api/verification/corrections",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({employmentRecordId:id,approved,notes})});const d=await r.json();setBusy("");setMessage(r.ok?(approved?"Corrected experience re-verified.":"Re-verification declined."):d.error||"Update failed");if(r.ok)load()};
 return <div className="wrap"><nav className="nav"><Link className="brand" href="/employer"><span>Career</span>Verify</Link><Link className="btn alt" href="/employer">Employer Dashboard</Link></nav>
 <div className="card"><div className="pill">PRIOR EMPLOYER</div><h1>Incoming verification</h1><p className="muted">Review employee requests, self-added records and corrected verified experiences.</p>{message&&<p className="notice">{message}</p>}</div>
 <section className="section"><h2>Additional information requests</h2>{loading?<p className="muted">Loading…</p>:additional.length?<div className="grid">{additional.map(x=><div className="card" key={x.id}><div className="pill">{x.status}</div><h3>{x.employeeName}</h3><p>Career ID: <strong>{x.careerId}</strong></p><p>Requested by: {x.requestingOrganization}</p><p><strong>Question:</strong> {x.question}</p>{x.status==="PENDING"?<button className="btn" disabled={busy===x.id} onClick={()=>additionalAction(x.id)}>Provide Additional Information</button>:<p className="muted"><strong>Response:</strong> {x.response}</p>}</div>)}</div>:<div className="card"><h3>No additional information requests</h3><p className="muted">Requests from new employers for already verified experiences will appear here.</p></div>}</section>
 <section className="section"><h2>Corrected experiences awaiting re-verification</h2>{loading?<p className="muted">Loading…</p>:corrections.length?<div className="grid">{corrections.map(x=><div className="card" key={x.id}><div className="pill">RE-VERIFICATION PENDING</div><h3>{x.employeeName}</h3><p>Career ID: <strong>{x.careerId}</strong></p><p><strong>{x.designation}</strong>{x.department?" • "+x.department:""}</p><p>{new Date(x.joinedAt).toLocaleDateString()} – {x.leftAt?new Date(x.leftAt).toLocaleDateString():"Present"}</p><p className="muted">Updated {new Date(x.pendingSince).toLocaleDateString()}. Review the corrected details before confirming.</p><div className="actions"><button className="btn" disabled={busy===x.id} onClick={()=>correctionAction(x.id,true)}>Re-verify corrected experience</button><button className="btn alt" disabled={busy===x.id} onClick={()=>correctionAction(x.id,false)}>Do not verify</button></div></div>)}</div>:<div className="card"><h3>No corrected experiences pending</h3><p className="muted">Employee corrections approved by your organization will appear here.</p></div>}</section>
 <section className="section"><h2>Self-added employment awaiting verification</h2>{loading?<p className="muted">Loading…</p>:self.length?<div className="grid">{self.map(x=><div className="card" key={x.id}><div className="pill">PENDING EMPLOYER REVIEW</div><h3>{x.employeeName}</h3><p>Career ID: <strong>{x.careerId}</strong></p><p>{x.designation}{x.department?" • "+x.department:""}</p><p>{new Date(x.joinedAt).toLocaleDateString()} – {x.leftAt?new Date(x.leftAt).toLocaleDateString():"Present"}</p>{x.employeeCode&&<p>Employee ID: {x.employeeCode}</p>}{x.remarks&&<p className="muted">{x.remarks}</p>}<div className="actions"><button className="btn" disabled={busy===x.id} onClick={()=>selfAction(x.id,"VERIFY")}>Verify experience</button><button className="btn alt" disabled={busy===x.id} onClick={()=>selfAction(x.id,"REJECT")}>Reject</button></div></div>)}</div>:<div className="card"><h3>No self-added records pending</h3><p className="muted">Employee-added past experience linked to your organization will appear here.</p></div>}</section>
 <section className="section"><h2>Incoming verification requests</h2>{loading?<p className="muted">Loading…</p>:items.length?<div className="grid">{items.map(x=><div className="card" key={x.id}><div className="pill">{x.status}</div><h3>{x.employeeName}</h3><p>Career ID: <strong>{x.careerId}</strong></p>{x.status==="PENDING"&&!x.response?(x.consentedAt?<div><p className="muted">Employee consent received.</p><div className="actions"><button className="btn" disabled={busy===x.id} onClick={()=>respond(x,true)}>Verify</button><button className="btn alt" disabled={busy===x.id} onClick={()=>respond(x,false)}>Reject</button></div></div>:<p className="muted">Waiting for employee consent.</p>):x.response?<p>{x.response.verified?"Verified":"Rejected"}</p>:null}</div>)}</div>:<div className="card"><h3>No incoming requests</h3><p className="muted">Requests for your organization will appear here.</p></div>}</section></div>
}
