"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Org={id:string;name:string};
export default function Employer(){
 const [careerId,setCareerId]=useState(""),[orgs,setOrgs]=useState<Org[]>([]),[prior,setPrior]=useState<Org[]>([]),[orgId,setOrgId]=useState(""),[priorId,setPriorId]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/me").then(r=>r.json()).then(d=>{setOrgs(d.organizations||[]);if(d.organizations?.[0])setOrgId(d.organizations[0].id)})},[]);
 async function find(){setMessage("");setPrior([]);const r=await fetch("/api/verification/targets?careerId="+encodeURIComponent(careerId));const d=await r.json();if(!r.ok){setMessage(d.error||"Career ID lookup failed");return}setPrior(d);if(d[0])setPriorId(d[0].id);}
 async function request(){setBusy(true);setMessage("");const r=await fetch("/api/verification/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({careerId,requestingOrgId:orgId,priorOrgId:priorId})});const d=await r.json();setBusy(false);setMessage(r.ok?"Verification request created. The employee must provide consent before the prior employer can respond.":d.error||"Request failed");}
 return <div className="wrap"><nav className="nav"><Link className="brand" href="/">Career<span>Verify</span></Link><Link className="btn alt" href="/verify">Verify Career ID</Link></nav><div className="card"><div className="pill">EMPLOYER WORKSPACE</div><h1>Employment verification</h1><p className="muted">Create a consent-backed verification request using a Career ID.</p>{orgs.length?<><div className="field"><label>Requesting organization</label><select value={orgId} onChange={e=>setOrgId(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div><div className="field"><label>Career ID</label><input value={careerId} onChange={e=>setCareerId(e.target.value)} placeholder="CV-IND-..."/></div><button className="btn alt" type="button" onClick={find} disabled={!careerId}>Find prior employers</button>{prior.length>0&&<><div className="field"><label>Prior employer</label><select value={priorId} onChange={e=>setPriorId(e.target.value)}>{prior.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div><button className="btn" type="button" onClick={request} disabled={busy||!priorId}>{busy?"Creating…":"Request verification"}</button></> } </>:<div className="notice">No organization is linked to this employer account yet.</div>}{message&&<p className="notice">{message}</p>}</div></div>
}