"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Org={id:string;name:string};
type Result={total:number;valid?:number;invalid?:number;imported?:number;errors?:{row:number;errors?:string[];error?:string}[];preview?:Record<string,unknown>[];failed?:{row:number;error:string}[]};
const targets=["name","companyEmail","phone","employeeCode","designation","department","joiningDate","employmentType","externalEmployeeId"];

export default function ImportPage(){
 const [orgs,setOrgs]=useState<Org[]>([]),[orgId,setOrgId]=useState(""),[rows,setRows]=useState<Record<string,string>[]>([]),[headers,setHeaders]=useState<string[]>([]),[map,setMap]=useState<Record<string,string>>({}),[result,setResult]=useState<Result|null>(null),[history,setHistory]=useState<unknown[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/me").then(r=>r.json()).then(d=>{setOrgs(d.organizations||[]);if(d.organizations?.[0]){setOrgId(d.organizations[0].id);loadHistory(d.organizations[0].id)}})},[]);
 async function loadHistory(id:string){const r=await fetch("/api/hrms/import/history?organizationId="+encodeURIComponent(id));setHistory(r.ok?await r.json():[])}
 async function parseFile(file:File){setBusy(true);const fd=new FormData();fd.append("organizationId",orgId);fd.append("file",file);const r=await fetch("/api/hrms/import/parse",{method:"POST",body:fd});const d=await r.json();if(!r.ok){setMsg(d.error||"Unable to read file.");setBusy(false);return}setHeaders(d.headers||[]);setRows(d.rows||[]);const initial:Record<string,string>={};targets.forEach(t=>{const h=(d.headers||[]).find((x:string)=>x.toLowerCase().replace(/[^a-z]/g,"")===t.toLowerCase().replace(/[^a-z]/g,""));if(h)initial[t]=h});setMap(initial);setResult(null);setMsg(d.fileName+" loaded: "+d.total+" rows.");setBusy(false)}
 function mapped(){return rows.map(r=>Object.fromEntries(targets.map(t=>[t,map[t]?String(r[map[t]]??""):""])))}
 async function validate(){setBusy(true);const r=await fetch("/api/hrms/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:orgId,rows:mapped()})});const d=await r.json();setResult(d);setMsg(r.ok?"Validation complete.":"Validation failed.");setBusy(false)}
 async function importRows(){setBusy(true);const r=await fetch("/api/hrms/import",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:orgId,rows:mapped().slice(0,result?.valid||0)})});const d=await r.json();setResult(d);setMsg(r.ok?"Import completed.":"Import failed.");setBusy(false);loadHistory(orgId)}
 return <div className="wrap"><nav className="nav"><Link className="brand" href="/hrms">Career<span>Verify</span></Link><Link className="btn alt" href="/hrms/employees">Employees</Link><Link className="btn alt" href="/hrms/integrations">Integrations</Link></nav>
 <div className="card"><div className="pill">MIGRATION CENTER</div><h1>Bulk employee import</h1><p className="muted">CSV / Excel import with column mapping, validation, preview and import history.</p>{orgs.length>1&&<div className="field"><label>Company</label><select value={orgId} onChange={e=>{setOrgId(e.target.value);loadHistory(e.target.value)}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div>}<div className="field"><label>CSV / Excel file</label><input type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>{const f=e.target.files?.[0];if(f)parseFile(f)}}/></div>{msg&&<p className="notice">{msg}</p>}</div>
 {headers.length>0&&<section className="section"><div className="card"><h2>Column mapping</h2><div className="grid">{targets.map(t=><div className="field" key={t}><label>{t}</label><select value={map[t]||""} onChange={e=>setMap({...map,[t]:e.target.value})}><option value="">Not mapped</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></div>)}</div><button className="btn" onClick={validate} disabled={busy||!orgId}>{busy?"Validating…":"Validate & preview"}</button></div></section>}
 {result&&<section className="section"><div className="card"><h2>Validation result</h2><p>Total: {result.total} • Valid: {result.valid??"—"} • Invalid: {result.invalid??result.failed?.length??"—"}</p>{result.errors?.length?<div className="card"><h3>Errors</h3>{result.errors.slice(0,50).map(e=><p key={e.row}>Row {e.row}: {(e.errors||[]).join(", ")}</p>)}</div>:null}{result.valid? <button className="btn" onClick={importRows} disabled={busy}>{busy?"Importing…":"Import valid rows"}</button>:null}{result.imported!==undefined&&<p className="notice">Imported: {result.imported}. Failed: {result.failed?.length||0}.</p>}</div></section>}
 <section className="section"><div className="card"><h2>Import history</h2>{history.length?history.map((h:any)=><p key={h.id} className="muted">{new Date(h.createdAt).toLocaleString()} • {h.metadata?.imported||0} imported • {h.metadata?.failed||0} failed</p>):<p className="muted">No imports yet.</p>}</div></section>
 </div>
}